/* soapServer.cpp
   Generated by gSOAP 2.7.17 from api.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.7.17 2016-01-13 17:01:41 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif

	do
	{
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			soap->error = SOAP_EOF;
			return soap_send_fault(soap);
		}
#endif

		soap_begin(soap);

#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif

		if (soap_begin_recv(soap))
		{	if (soap->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(soap);
#else 
				return soap_send_fault(soap);
#endif
			}
			soap_closesock(soap);

			continue;
		}

		if (soap_envelope_begin_in(soap)
		 || soap_recv_header(soap)
		 || soap_body_begin_in(soap)
		 || soap_serve_request(soap)
		 || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:authenticateSession"))
		return soap_serve___ns1__authenticateSession(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:deleteExecution"))
		return soap_serve___ns1__deleteExecution(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getPipeline"))
		return soap_serve___ns1__getPipeline(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:authenticateHTTP"))
		return soap_serve___ns1__authenticateHTTP(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:logout"))
		return soap_serve___ns1__logout(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:updateExecution"))
		return soap_serve___ns1__updateExecution(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getGlobalProperties"))
		return soap_serve___ns1__getGlobalProperties(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:initExecution"))
		return soap_serve___ns1__initExecution(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getStdOut"))
		return soap_serve___ns1__getStdOut(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getStdErr"))
		return soap_serve___ns1__getStdErr(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getExecutionResults"))
		return soap_serve___ns1__getExecutionResults(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:killExecution"))
		return soap_serve___ns1__killExecution(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getExecution"))
		return soap_serve___ns1__getExecution(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:playExecution"))
		return soap_serve___ns1__playExecution(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:listPipelines"))
		return soap_serve___ns1__listPipelines(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:listExecutions"))
		return soap_serve___ns1__listExecutions(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__authenticateSession(struct soap *soap)
{	struct __ns1__authenticateSession soap_tmp___ns1__authenticateSession;
	ns1__authenticateSessionResponse ns1__authenticateSessionResponse_;
	ns1__authenticateSessionResponse_.soap_default(soap);
	soap_default___ns1__authenticateSession(soap, &soap_tmp___ns1__authenticateSession);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__authenticateSession(soap, &soap_tmp___ns1__authenticateSession, "-ns1:authenticateSession", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__authenticateSession(soap, soap_tmp___ns1__authenticateSession.ns1__authenticateSession_, &ns1__authenticateSessionResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__authenticateSessionResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__authenticateSessionResponse_.soap_put(soap, "ns1:authenticateSessionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__authenticateSessionResponse_.soap_put(soap, "ns1:authenticateSessionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__deleteExecution(struct soap *soap)
{	struct __ns1__deleteExecution soap_tmp___ns1__deleteExecution;
	ns1__deleteExecutionResponse ns1__deleteExecutionResponse_;
	ns1__deleteExecutionResponse_.soap_default(soap);
	soap_default___ns1__deleteExecution(soap, &soap_tmp___ns1__deleteExecution);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__deleteExecution(soap, &soap_tmp___ns1__deleteExecution, "-ns1:deleteExecution", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__deleteExecution(soap, soap_tmp___ns1__deleteExecution.ns1__deleteExecution_, &ns1__deleteExecutionResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__deleteExecutionResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__deleteExecutionResponse_.soap_put(soap, "ns1:deleteExecutionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__deleteExecutionResponse_.soap_put(soap, "ns1:deleteExecutionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getPipeline(struct soap *soap)
{	struct __ns1__getPipeline soap_tmp___ns1__getPipeline;
	ns1__getPipelineResponse ns1__getPipelineResponse_;
	ns1__getPipelineResponse_.soap_default(soap);
	soap_default___ns1__getPipeline(soap, &soap_tmp___ns1__getPipeline);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__getPipeline(soap, &soap_tmp___ns1__getPipeline, "-ns1:getPipeline", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__getPipeline(soap, soap_tmp___ns1__getPipeline.ns1__getPipeline_, &ns1__getPipelineResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__getPipelineResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__getPipelineResponse_.soap_put(soap, "ns1:getPipelineResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__getPipelineResponse_.soap_put(soap, "ns1:getPipelineResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__authenticateHTTP(struct soap *soap)
{	struct __ns1__authenticateHTTP soap_tmp___ns1__authenticateHTTP;
	ns1__authenticateHTTPResponse ns1__authenticateHTTPResponse_;
	ns1__authenticateHTTPResponse_.soap_default(soap);
	soap_default___ns1__authenticateHTTP(soap, &soap_tmp___ns1__authenticateHTTP);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__authenticateHTTP(soap, &soap_tmp___ns1__authenticateHTTP, "-ns1:authenticateHTTP", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__authenticateHTTP(soap, soap_tmp___ns1__authenticateHTTP.ns1__authenticateHTTP_, &ns1__authenticateHTTPResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__authenticateHTTPResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__authenticateHTTPResponse_.soap_put(soap, "ns1:authenticateHTTPResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__authenticateHTTPResponse_.soap_put(soap, "ns1:authenticateHTTPResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__logout(struct soap *soap)
{	struct __ns1__logout soap_tmp___ns1__logout;
	ns1__logoutResponse ns1__logoutResponse_;
	ns1__logoutResponse_.soap_default(soap);
	soap_default___ns1__logout(soap, &soap_tmp___ns1__logout);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__logout(soap, &soap_tmp___ns1__logout, "-ns1:logout", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__logout(soap, soap_tmp___ns1__logout.ns1__logout_, &ns1__logoutResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__logoutResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__logoutResponse_.soap_put(soap, "ns1:logoutResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__logoutResponse_.soap_put(soap, "ns1:logoutResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__updateExecution(struct soap *soap)
{	struct __ns1__updateExecution soap_tmp___ns1__updateExecution;
	ns1__updateExecutionResponse ns1__updateExecutionResponse_;
	ns1__updateExecutionResponse_.soap_default(soap);
	soap_default___ns1__updateExecution(soap, &soap_tmp___ns1__updateExecution);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__updateExecution(soap, &soap_tmp___ns1__updateExecution, "-ns1:updateExecution", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__updateExecution(soap, soap_tmp___ns1__updateExecution.ns1__updateExecution_, &ns1__updateExecutionResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__updateExecutionResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__updateExecutionResponse_.soap_put(soap, "ns1:updateExecutionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__updateExecutionResponse_.soap_put(soap, "ns1:updateExecutionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getGlobalProperties(struct soap *soap)
{	struct __ns1__getGlobalProperties soap_tmp___ns1__getGlobalProperties;
	ns1__getGlobalPropertiesResponse ns1__getGlobalPropertiesResponse_;
	ns1__getGlobalPropertiesResponse_.soap_default(soap);
	soap_default___ns1__getGlobalProperties(soap, &soap_tmp___ns1__getGlobalProperties);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__getGlobalProperties(soap, &soap_tmp___ns1__getGlobalProperties, "-ns1:getGlobalProperties", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__getGlobalProperties(soap, soap_tmp___ns1__getGlobalProperties.ns1__getGlobalProperties_, &ns1__getGlobalPropertiesResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__getGlobalPropertiesResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__getGlobalPropertiesResponse_.soap_put(soap, "ns1:getGlobalPropertiesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__getGlobalPropertiesResponse_.soap_put(soap, "ns1:getGlobalPropertiesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__initExecution(struct soap *soap)
{	struct __ns1__initExecution soap_tmp___ns1__initExecution;
	ns1__initExecutionResponse ns1__initExecutionResponse_;
	ns1__initExecutionResponse_.soap_default(soap);
	soap_default___ns1__initExecution(soap, &soap_tmp___ns1__initExecution);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__initExecution(soap, &soap_tmp___ns1__initExecution, "-ns1:initExecution", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__initExecution(soap, soap_tmp___ns1__initExecution.ns1__initExecution_, &ns1__initExecutionResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__initExecutionResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__initExecutionResponse_.soap_put(soap, "ns1:initExecutionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__initExecutionResponse_.soap_put(soap, "ns1:initExecutionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getStdOut(struct soap *soap)
{	struct __ns1__getStdOut soap_tmp___ns1__getStdOut;
	ns1__getStdOutResponse ns1__getStdOutResponse_;
	ns1__getStdOutResponse_.soap_default(soap);
	soap_default___ns1__getStdOut(soap, &soap_tmp___ns1__getStdOut);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__getStdOut(soap, &soap_tmp___ns1__getStdOut, "-ns1:getStdOut", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__getStdOut(soap, soap_tmp___ns1__getStdOut.ns1__getStdOut_, &ns1__getStdOutResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__getStdOutResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__getStdOutResponse_.soap_put(soap, "ns1:getStdOutResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__getStdOutResponse_.soap_put(soap, "ns1:getStdOutResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getStdErr(struct soap *soap)
{	struct __ns1__getStdErr soap_tmp___ns1__getStdErr;
	ns1__getStdErrResponse ns1__getStdErrResponse_;
	ns1__getStdErrResponse_.soap_default(soap);
	soap_default___ns1__getStdErr(soap, &soap_tmp___ns1__getStdErr);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__getStdErr(soap, &soap_tmp___ns1__getStdErr, "-ns1:getStdErr", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__getStdErr(soap, soap_tmp___ns1__getStdErr.ns1__getStdErr_, &ns1__getStdErrResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__getStdErrResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__getStdErrResponse_.soap_put(soap, "ns1:getStdErrResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__getStdErrResponse_.soap_put(soap, "ns1:getStdErrResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getExecutionResults(struct soap *soap)
{	struct __ns1__getExecutionResults soap_tmp___ns1__getExecutionResults;
	ns1__getExecutionResultsResponse ns1__getExecutionResultsResponse_;
	ns1__getExecutionResultsResponse_.soap_default(soap);
	soap_default___ns1__getExecutionResults(soap, &soap_tmp___ns1__getExecutionResults);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__getExecutionResults(soap, &soap_tmp___ns1__getExecutionResults, "-ns1:getExecutionResults", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__getExecutionResults(soap, soap_tmp___ns1__getExecutionResults.ns1__getExecutionResults_, &ns1__getExecutionResultsResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__getExecutionResultsResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__getExecutionResultsResponse_.soap_put(soap, "ns1:getExecutionResultsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__getExecutionResultsResponse_.soap_put(soap, "ns1:getExecutionResultsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__killExecution(struct soap *soap)
{	struct __ns1__killExecution soap_tmp___ns1__killExecution;
	ns1__killExecutionResponse ns1__killExecutionResponse_;
	ns1__killExecutionResponse_.soap_default(soap);
	soap_default___ns1__killExecution(soap, &soap_tmp___ns1__killExecution);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__killExecution(soap, &soap_tmp___ns1__killExecution, "-ns1:killExecution", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__killExecution(soap, soap_tmp___ns1__killExecution.ns1__killExecution_, &ns1__killExecutionResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__killExecutionResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__killExecutionResponse_.soap_put(soap, "ns1:killExecutionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__killExecutionResponse_.soap_put(soap, "ns1:killExecutionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getExecution(struct soap *soap)
{	struct __ns1__getExecution soap_tmp___ns1__getExecution;
	ns1__getExecutionResponse ns1__getExecutionResponse_;
	ns1__getExecutionResponse_.soap_default(soap);
	soap_default___ns1__getExecution(soap, &soap_tmp___ns1__getExecution);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__getExecution(soap, &soap_tmp___ns1__getExecution, "-ns1:getExecution", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__getExecution(soap, soap_tmp___ns1__getExecution.ns1__getExecution_, &ns1__getExecutionResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__getExecutionResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__getExecutionResponse_.soap_put(soap, "ns1:getExecutionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__getExecutionResponse_.soap_put(soap, "ns1:getExecutionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__playExecution(struct soap *soap)
{	struct __ns1__playExecution soap_tmp___ns1__playExecution;
	ns1__playExecutionResponse ns1__playExecutionResponse_;
	ns1__playExecutionResponse_.soap_default(soap);
	soap_default___ns1__playExecution(soap, &soap_tmp___ns1__playExecution);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__playExecution(soap, &soap_tmp___ns1__playExecution, "-ns1:playExecution", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__playExecution(soap, soap_tmp___ns1__playExecution.ns1__playExecution_, &ns1__playExecutionResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__playExecutionResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__playExecutionResponse_.soap_put(soap, "ns1:playExecutionResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__playExecutionResponse_.soap_put(soap, "ns1:playExecutionResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__listPipelines(struct soap *soap)
{	struct __ns1__listPipelines soap_tmp___ns1__listPipelines;
	ns1__listPipelinesResponse ns1__listPipelinesResponse_;
	ns1__listPipelinesResponse_.soap_default(soap);
	soap_default___ns1__listPipelines(soap, &soap_tmp___ns1__listPipelines);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__listPipelines(soap, &soap_tmp___ns1__listPipelines, "-ns1:listPipelines", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__listPipelines(soap, soap_tmp___ns1__listPipelines.ns1__listPipelines_, &ns1__listPipelinesResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__listPipelinesResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__listPipelinesResponse_.soap_put(soap, "ns1:listPipelinesResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__listPipelinesResponse_.soap_put(soap, "ns1:listPipelinesResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__listExecutions(struct soap *soap)
{	struct __ns1__listExecutions soap_tmp___ns1__listExecutions;
	ns1__listExecutionsResponse ns1__listExecutionsResponse_;
	ns1__listExecutionsResponse_.soap_default(soap);
	soap_default___ns1__listExecutions(soap, &soap_tmp___ns1__listExecutions);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__listExecutions(soap, &soap_tmp___ns1__listExecutions, "-ns1:listExecutions", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__listExecutions(soap, soap_tmp___ns1__listExecutions.ns1__listExecutions_, &ns1__listExecutionsResponse_);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__listExecutionsResponse_.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__listExecutionsResponse_.soap_put(soap, "ns1:listExecutionsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__listExecutionsResponse_.soap_put(soap, "ns1:listExecutionsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.cpp */
