/* soapCarminSoapBindingProxy.h
   Generated by gSOAP 2.7.17 from api.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapCarminSoapBindingProxy_H
#define soapCarminSoapBindingProxy_H
#include "soapH.h"
class CarminSoapBinding
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'CarminSoapBinding' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	CarminSoapBinding()
	{ soap = soap_new(); endpoint = "http://localhost/api"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://france-life-imaging.fr/api", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~CarminSoapBinding() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'authenticateSession' of service 'CarminSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__authenticateSession(ns1__authenticateSession *ns1__authenticateSession_, ns1__authenticateSessionResponse *ns1__authenticateSessionResponse_) { return soap ? soap_call___ns1__authenticateSession(soap, endpoint, NULL, ns1__authenticateSession_, ns1__authenticateSessionResponse_) : SOAP_EOM; };
	/// Invoke 'deleteExecution' of service 'CarminSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__deleteExecution(ns1__deleteExecution *ns1__deleteExecution_, ns1__deleteExecutionResponse *ns1__deleteExecutionResponse_) { return soap ? soap_call___ns1__deleteExecution(soap, endpoint, NULL, ns1__deleteExecution_, ns1__deleteExecutionResponse_) : SOAP_EOM; };
	/// Invoke 'getPipeline' of service 'CarminSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getPipeline(ns1__getPipeline *ns1__getPipeline_, ns1__getPipelineResponse *ns1__getPipelineResponse_) { return soap ? soap_call___ns1__getPipeline(soap, endpoint, NULL, ns1__getPipeline_, ns1__getPipelineResponse_) : SOAP_EOM; };
	/// Invoke 'authenticateHTTP' of service 'CarminSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__authenticateHTTP(ns1__authenticateHTTP *ns1__authenticateHTTP_, ns1__authenticateHTTPResponse *ns1__authenticateHTTPResponse_) { return soap ? soap_call___ns1__authenticateHTTP(soap, endpoint, NULL, ns1__authenticateHTTP_, ns1__authenticateHTTPResponse_) : SOAP_EOM; };
	/// Invoke 'logout' of service 'CarminSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__logout(ns1__logout *ns1__logout_, ns1__logoutResponse *ns1__logoutResponse_) { return soap ? soap_call___ns1__logout(soap, endpoint, NULL, ns1__logout_, ns1__logoutResponse_) : SOAP_EOM; };
	/// Invoke 'updateExecution' of service 'CarminSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__updateExecution(ns1__updateExecution *ns1__updateExecution_, ns1__updateExecutionResponse *ns1__updateExecutionResponse_) { return soap ? soap_call___ns1__updateExecution(soap, endpoint, NULL, ns1__updateExecution_, ns1__updateExecutionResponse_) : SOAP_EOM; };
	/// Invoke 'getGlobalProperties' of service 'CarminSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getGlobalProperties(ns1__getGlobalProperties *ns1__getGlobalProperties_, ns1__getGlobalPropertiesResponse *ns1__getGlobalPropertiesResponse_) { return soap ? soap_call___ns1__getGlobalProperties(soap, endpoint, NULL, ns1__getGlobalProperties_, ns1__getGlobalPropertiesResponse_) : SOAP_EOM; };
	/// Invoke 'initExecution' of service 'CarminSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__initExecution(ns1__initExecution *ns1__initExecution_, ns1__initExecutionResponse *ns1__initExecutionResponse_) { return soap ? soap_call___ns1__initExecution(soap, endpoint, NULL, ns1__initExecution_, ns1__initExecutionResponse_) : SOAP_EOM; };
	/// Invoke 'getStdOut' of service 'CarminSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getStdOut(ns1__getStdOut *ns1__getStdOut_, ns1__getStdOutResponse *ns1__getStdOutResponse_) { return soap ? soap_call___ns1__getStdOut(soap, endpoint, NULL, ns1__getStdOut_, ns1__getStdOutResponse_) : SOAP_EOM; };
	/// Invoke 'getStdErr' of service 'CarminSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getStdErr(ns1__getStdErr *ns1__getStdErr_, ns1__getStdErrResponse *ns1__getStdErrResponse_) { return soap ? soap_call___ns1__getStdErr(soap, endpoint, NULL, ns1__getStdErr_, ns1__getStdErrResponse_) : SOAP_EOM; };
	/// Invoke 'getExecutionResults' of service 'CarminSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getExecutionResults(ns1__getExecutionResults *ns1__getExecutionResults_, ns1__getExecutionResultsResponse *ns1__getExecutionResultsResponse_) { return soap ? soap_call___ns1__getExecutionResults(soap, endpoint, NULL, ns1__getExecutionResults_, ns1__getExecutionResultsResponse_) : SOAP_EOM; };
	/// Invoke 'killExecution' of service 'CarminSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__killExecution(ns1__killExecution *ns1__killExecution_, ns1__killExecutionResponse *ns1__killExecutionResponse_) { return soap ? soap_call___ns1__killExecution(soap, endpoint, NULL, ns1__killExecution_, ns1__killExecutionResponse_) : SOAP_EOM; };
	/// Invoke 'getExecution' of service 'CarminSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__getExecution(ns1__getExecution *ns1__getExecution_, ns1__getExecutionResponse *ns1__getExecutionResponse_) { return soap ? soap_call___ns1__getExecution(soap, endpoint, NULL, ns1__getExecution_, ns1__getExecutionResponse_) : SOAP_EOM; };
	/// Invoke 'playExecution' of service 'CarminSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__playExecution(ns1__playExecution *ns1__playExecution_, ns1__playExecutionResponse *ns1__playExecutionResponse_) { return soap ? soap_call___ns1__playExecution(soap, endpoint, NULL, ns1__playExecution_, ns1__playExecutionResponse_) : SOAP_EOM; };
	/// Invoke 'listPipelines' of service 'CarminSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__listPipelines(ns1__listPipelines *ns1__listPipelines_, ns1__listPipelinesResponse *ns1__listPipelinesResponse_) { return soap ? soap_call___ns1__listPipelines(soap, endpoint, NULL, ns1__listPipelines_, ns1__listPipelinesResponse_) : SOAP_EOM; };
	/// Invoke 'listExecutions' of service 'CarminSoapBinding' and return error code (or SOAP_OK)
	virtual int __ns1__listExecutions(ns1__listExecutions *ns1__listExecutions_, ns1__listExecutionsResponse *ns1__listExecutionsResponse_) { return soap ? soap_call___ns1__listExecutions(soap, endpoint, NULL, ns1__listExecutions_, ns1__listExecutionsResponse_) : SOAP_EOM; };
};
#endif
